### ISSUE TITLE
Early Research

### ISSUE THREAD

**Issue by sergfeldman** [ubiquity/series-a#2]
We should build relationships with these organizations. I took some inspiration from FEI because their investors singlehandedly are the reason (besides the market conditions) why they were able to raise a billion in on-chain liquidity in 24 hours. 

### Hitlist

We first need to figure out what type of pitch will appeal to the following, and see if it makes sense to bring them on our cap table for the DevPool/Dollar

#### Tier I

- [ ] Develop Pitch: GnosisDAO
- [ ] Develop Pitch: GitHub/Microsoft
- [ ] Develop Pitch: Paradigm
- [ ] Develop Pitch: Visa/MasterCard
- [ ] Develop Pitch: Coinbase Ventures
- [ ] Develop Pitch: a16z Crypto
- [ ] Develop Pitch: Sequoia Capital

#### Tier II

- [ ] Develop Pitch: Framework Ventures
- [ ] Develop Pitch: Variant
- [ ] Develop Pitch: ParaFi
- [ ] Develop Pitch: Naval Ravikant

### Schedule
Six Months: March 2024 - September 2024
### Terms
- 10% at $100M - $200M USD valuation
  - Previously 10% at $20M USD valuation
### Milestones
These could help us with increasing our valuation.
- [ ] Ubiquity Dollar launch with collateral
- [x] https://github.com/ubiquity/research/issues/2
- [x] https://github.com/ubiquity/research/issues/6
- [ ] The launch of UbiquiCards

### Appendix

- [x] https://github.com/ubiquity/research/issues/3

**Comment by 0x4007** [comment]
@sergfeldman make checklists and then tag issues so that GitHub automatically expands the issue name, making this far more readable. I edited your post to provide an example. 

It is important to focus on making these maximally readable or else it is extraordinarily difficult to get contributors to participate. Make these as concise and accurate as possible. More words, more proposals, and more bounties than necessary (unless properly organized and tucked away) are not good.

Lastly, you should be only assigned to one (max two) tasks at a time.

**Comment by sergfeldman** [comment]
> @sergfeldman make checklists and then tag issues so that GitHub automatically expands the issue name, making this far more readable. I edited your post to provide an example.
> 
> It is important to focus on making these maximally readable or else it is extraordinarily difficult to get contributors to participate. Make these as concise and accurate as possible. More words, more proposals, and more bounties than necessary (unless properly organized and tucked away) are not good.

@pavlovcik Thank you very much for the recommendations and for the example!
I will try to follow your recommendations.

I would like to draw your attention to the fact that this particular task is not assigned to me.
Actually, I thought it would be assigned to you :)

The reason why I initially created this task was to get your input on Series A. This was done.

**Comment by sergfeldman** [comment]
> Lastly, you should be only assigned to one (max two) tasks at a time.

@pavlovcik I guess, you see 9 tasks assigned to me and think that I am not focused. 
https://github.com/orgs/ubiquity/projects/24/views/1?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Labels

Let me describe the status and then please tell me what I should change. 

**Over the past week, I completed 3 tasks for our discussion** and now they are in the status "To discuss"
https://github.com/orgs/ubiquity/projects/24/views/1?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Labels&filterQuery=assignee%3Asergfeldman+status%3A%22To+discuss%22

3 tasks are in the "Not ready for discussion" status.
**I am actively conducting research for 1 of them now.**
For 2 others I put down some information to start thinking. I am not actively engaged in both of them now.
I plan to do them in the near future because I think they are important for Series A.
https://github.com/orgs/ubiquity/projects/24/views/1?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Labels&filterQuery=assignee%3Asergfeldman+status%3A%22Not+ready+for+discussion%22

2 tasks have already been discussed earlier and are in the "In review" status
https://github.com/orgs/ubiquity/projects/24/views/1?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Labels&filterQuery=assignee%3Asergfeldman+status%3A%22In+review%22

1 task has already been discussed earlier and is in the "Backlog" status
https://github.com/orgs/ubiquity/projects/24/views/1?sortedBy%5Bdirection%5D=desc&sortedBy%5BcolumnId%5D=Labels&filterQuery=assignee%3Asergfeldman+status%3ABacklog
